name: Maven CI Workflow

on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Build the project with Maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      # Run the Java application to check if it's working
      - name: Run Java application
        run: |
          if [ -f target/jb-hello-world-maven-0.2.0-shaded.jar ]; then
            java -cp target/jb-hello-world-maven-0.2.0-shaded.jar hello.HelloWorld
          else
            echo "JAR file not found!"
            exit 1
          fi
