name: Maven CI Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Build the project with Maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      # List files in target directory to debug
      - name: List files in target directory
        run: ls -l $GITHUB_WORKSPACE/target

      # Run the Java application using the shaded JAR
      - name: Run Java application
        run: |
          JAR_PATH="$GITHUB_WORKSPACE/target/jb-hello-world-maven-0.2.0-shaded.jar"
          if [ -f "$JAR_PATH" ]; then
            java -cp "$JAR_PATH" hello.HelloWorld
          else
            echo "Shaded JAR file not found at $JAR_PATH"
            exit 1
          fi
