name: Maven CI Workflow

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Restore Maven cache
      - name:  Maven cache
        id:  mvn-cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-maven-

      - name: install dependencies
        if: steps.mvn-cache.outputs.cache-hit != 'true'
        run: mvn clean install

      # Build the project with Maven
      - name: Build with Maven
        run: mvn package

     
      # List files in target directory to debug
      - name: List files in target directory
        run: ls -l $GITHUB_WORKSPACE/target

      # Run the Java application using the JAR file
      - name: Run Java application
        run: |
          JAR_PATH="$GITHUB_WORKSPACE/target/jb-hello-world-maven-0.2.0.jar"
          if [ -f "$JAR_PATH" ]; then
            java -cp "$JAR_PATH" hello.HelloWorld
          else
            echo "JAR file not found at $JAR_PATH"
            exit 1
          fi
